### ISSUE TITLE
[Prüfungsvorbereitung] Beispielaufgabe zum Parallelisierungs-Kapitel

### ISSUE THREAD

**Issue by DManstrator** [ob-vss-ss18/ob-vss-ss18#10]
Sehr geehrter Herr Professor Braun,

wäre es möglich, dass Sie uns zum Üben für das Kapitel "Parallelisierung" ein paar Beispiel-Werte für Variablen vorgeben könnten, mit denen wir selbst ein Beispiel durchrechnen können? Einfach nur die Formeln in und auswendig zu lernen hilft mir persönlich weniger als es an Beispielen anzuwenden aber ich wüsste nicht, welchen Variablen ich welche Werte zuweisen sollte, um ein gutes Beispiel durchrechnen zu können. Oder gibt es eine Seite, die Sie zum Üben empfehlen können?

Mit freundlichen Grüßen

Daniel Gabl

**Comment by DManstrator** [comment]
PS: Ich habe keine Rechte in diesem Repository, kann Sie also nicht wie gewünscht als Assignee hinzufügen. @obcode

**Comment by obcode** [comment]
Ja, das mit den Rechten werde ich in Zukunft anders machen 😄 

Naja, was wollen Sie denn rechnen.

Nehmen Sie doch einfach was an, z.B. das sequentielle Programm braucht 120 Sekunden, das parallele auf 10 Prozessoren z.B. 15 Sekunden, dann wäre der Speedup
120 / 15 = 8.

Die Kosten wären dann aber 15 * 10 = 150. Also ist 30 der Overhead H_p(n).

Die Effizienz wiederum ist dann ist Speedup / Anzahl Prozessoren = 8 / 10 = 120 / (10 * 15) = T' / Kosten.

Nehmen wir mal an 1/3 des Programmes lässt sich nicht parallelisieren. Also f = 0,33333.
Nach Amdahl gilt dann der Speedup <= 1 / 0,3333 = 3. Das heisst also selbst mit 10000 Prozessoren wird ein Programm, das sequentiell 30 Minuten braucht, mindestens 10 Minuten brauchen.

Okay?

**Comment by DManstrator** [comment]
Sehr geehrter Herr Professor Braun,

vielen Dank für die schnelle Antwort und entschuldigen Sie bitte die späte Antwort meinerseits. Eigentlich hätte ich es gedacht, dass Sie nur Angaben als Beispiel geben (T'(n) = 120, T<sub>p</sub>(n) = 15, n = 10) und man selbst rechnen und dann auf Sie zurück kommen soll, daher noch einmal vielen Dank, dass Sie auch gleich die Erklärungen zum besseren Verstehen beigelegt haben, ich konnte Ihre Rechnung dadurch viel besser nachvollziehen.

Mit freundlichen Grüßen

Daniel Gabl
